### ISSUE TITLE
Map title and short title missing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#808] opened 2017-08-03 16:07 UTC
New map component doesn't display map title or short title for end user.

See boston.gov test page as example.

**Comment by jimafisk** [comment] 2017-12-08 21:08
This was a little tricky, so for future reference, in `docroot/sites/all/modules/custom/bos_core/bos_core.module` there is a function called `_bos_core_get_components()` (line 216) that defines a static list of all potential components. This function is called in `sites/all/themes/custom/boston/template.php` inside an `in_array()` function to check if the current paragraph bundle is in the list in order to set the variable `$is_component_field` to 1 (line 1938). That variable is checked in `boston_preprocess_field_field_component_title()` (line 1997) before creating values for `$short_title` and `$short_title_link` which are used in the template (`sites/all/themes/custom/boston/templates/field/field--field-component-title.tpl.php`) but are currently missing.

**Comment by jimafisk** [comment] 2017-12-27 19:23
Testing steps:
1. Create a new node, for this example we'll add a new Article (`/node/add/article`) and add test information for all required fields
2. Click on the "Components" tab in the left sidebar and add a "Map" under "Component type"
3. Fill out the required Map information, pay particular attention to the Title and Short Title fields
4. Publish and save the node
5. Make sure the in-page navigation (short title) is working and there is a visible Map title

Repeat for content types with component field (Landing Page, Guide, Department Profile, Article, Post, Event, Listing Page, Person Profile, How-To, Place Profile, Program Initiative Profile, Script Page, Public Notice).

<details>
  <summary>Testing gif (click to expand)</summary>

![map_short_title](https://user-images.githubusercontent.com/5913244/34390923-e34fc6d0-eb10-11e7-8f16-c8e39edbb5d0.gif)

</details>

**Comment by BrutiAnteneh** [comment] 2017-12-28 13:28
This issue did not pass as expected because it did not meet the following conditions:

The Map component is functioning correctly, *if*:
 1. Text entered into *both* the **Map Title field** *and the* **Map Short Title** field appears on the published page. (The issue fails if only one of them appears).
 2. Condition #1 is true for each content type carrying the Map component: Landing Page, Guide, Department Profile, Article, Post, Event, Listing Page, Person Profile, How-To, Place Profile, Program Initiative Profile, Script Page, Public Notice. 

| Content Type  | Map Title | Map Short Title  | URL |
| ------------- | ------------- | -------------| ------------- |
| Landing | x | - | [/landing-page-map-test](https://edit-stg.boston.gov/landing-page-map-test) |
| Guide | x | - | [/guide-page-map-test](https://edit-stg.boston.gov/guide-page-map-test) |
| Department | x | x | [/departments/archaeology/person-profile-map-test](https://edit-stg.boston.gov/departments/department-page-map-test) |
| Article | x | x | [/article-page-map-test](https://edit-stg.boston.gov/article-page-map-test) |
| Post | x | x | [/news/post-maps-test](https://edit-stg.boston.gov/news/post-map-test) |
| Event | x | - | [/calendar/event-page-map-test](https://edit-stg.boston.gov/calendar/event-page-map-test) |
| Listing Page | x | - | [/listing-page-map-test](https://edit-stg.boston.gov/listing-page-map-test) | 
| Person Profile | x | - | [/departments/archaeology/person-profile-map-test](https://edit-stg.boston.gov/departments/archaeology/person-profile-map-test) |
| How-To | x | - | [/how-map-test](https://edit-stg.boston.gov/how-map-test) |
| Place Profile | x | - | [/cemetaries/place-profile-map-test](https://edit-stg.boston.gov/cemetaries/place-profile-map-test) |
| Program Profile | x | x | [/arts-and-culture/program-initiative-profile-map-test](https://edit-stg.boston.gov/arts-and-culture/program-initiative-profile-map-test) |
| Script Page | x | - | [/script-page-map-test](https://edit-stg.boston.gov/script-page-map-test) |
| Public Notice | x | - |[ /public-notices/36261](https://edit-stg.boston.gov/public-notices/36261)|

**Comment by jimafisk** [comment] 2017-12-28 15:20
@BrutiAnteneh the level of detail you provided is excellent! Confirmed the short title (in-page nav) appears to be missing for several content types based on the examples you provided. Can you confirm whether or not other components with short titles (FYI, Drawers, Grid of Cards, etc) are working on these content types? I want to make sure the issue is isolated to the Maps component, and not short titles in general. If problem exists for other component short titles, can you pass this issue and open a new issue with details about which content types the short titles are broken for? Thank you!

**Closed** 2017-12-28 19:09 UTC
Labels: bug, minor
