### ISSUE TITLE
Spacing issue in sidebar component of article pages

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#853] opened 2017-09-01 16:00 UTC
Looks like we're missing the dashed line (or at least some padding) in between the "contact" section and the sidebar components on article pages:

![image](https://user-images.githubusercontent.com/7929556/29977677-3d30f23e-8f0c-11e7-9307-a726e1c6e13e.png)

This bug looks like it's only article pages because it's based off that automatic contact information that appears in the top right of the page. You fill out that field to make it appear in the top right here under "basic information":

![image](https://user-images.githubusercontent.com/7929556/29977853-cbd5db62-8f0c-11e7-90fa-90e5965093fd.png)

Also, the page I'm referencing is here:

https://www.boston.gov/departments/transportation/neighborhood-slow-streets/stonybrook

**Comment by jimafisk** [comment] 2017-09-01 19:54
@jduffy2001 it looks like the dashed border and padding for the last element in the sidebar was intentionally removed. Here is what it looks like without the code that overrides the style of that last item:

![with_default_border_and_padding](https://user-images.githubusercontent.com/5913244/29985597-a411ac70-8f2d-11e7-8ba7-376c794420d2.png)

Is that closer to what you envisioned?

**Comment by jimafisk** [comment] 2017-09-01 20:03
I believe this is a duplicate of issue #832. I'm going to close this issue and reference it there so this can be managed in one place. @jduffy2001 if I'm missing something and these are separate issue, just let me know. Thanks!

**Closed by jimafisk** 2017-09-01 20:03 UTC
Labels: bug
