### ISSUE TITLE
Bug: Intermittent breaks for transactions grid

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#510] opened 2017-03-09 20:33 UTC
There are intermittent breaks for transactions grid and group of links - grid [could be more but this is all we're able to recreate] happening when updates are being made to program/initiative pages and department profiles [again, could be more but this is all we're able to recreate]. Happens after page is saved/published once and when new draft is created happens on new draft.

Error message under 'link' says: "You are not allowed to remove this Link item."

Example pages this is known to have happened on:

- boston.gov/transportation/go-boston-2030 [program/initiative page] - experienced on 3/7/17
- boston.gov/departments/education-cabinet [department profile] - experienced on 3/9/17

Randomly able to resolve [particularly with new user testing].

Visual example of program/initiative page issue:

![image 2](https://cloud.githubusercontent.com/assets/20731897/23769711/3d755c66-04de-11e7-909a-5b0ae42afb08.png)

Visual example of department page issue:

![image 1](https://cloud.githubusercontent.com/assets/20731897/23769695/35cbad9e-04de-11e7-9c61-7c88ee024753.png)

**Comment by matthewcrist** [comment] 2017-03-22 13:14
I'm unable to reproduce this currently. We'll need to have it in a reproducible way before it can get fixed. Suggest moving to the backlog until we get that @reillyzlab.

**Comment by reillyzlab** [comment] 2017-03-22 13:34
@jduffy2001 please grab Matt and I if/when this happens so we can real time triage

**Comment by matthewcrist** [comment] 2017-08-29 13:49
This is a dupe #672. Closing in favor of that issue.

**Closed by matthewcrist** 2017-08-29 13:49 UTC
Labels: both sites, bug
