### ISSUE TITLE
Add 'tools' link to Hub header

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#244] opened 2016-12-01 18:31 UTC
Nearly 20% of page sessions involve users going to /tools immediately, which is about 15% more than other page types.

Goal: As a 'power users' I want to get to the applications [/tools] that I use most frequently more quickly.

Requirements:  
Add a 'quick link' to 'tool's at [Hub URL]/tools to Hub header.

Specifications on where to add/styling:

- Add this when a user is logged in to the left of the avatar as the word 'TOOLS' formatted like terms in the boston.gov header but using text color HEX: #378EA5:  
![formatting replica](https://cloud.githubusercontent.com/assets/20731897/20323167/a7763b1a-ab49-11e6-811b-49930d9f0a71.PNG)

- Replicate spacing that lies between the avatar and magnifying glass:  
![spacing](https://cloud.githubusercontent.com/assets/20731897/20323267/f3abcc0c-ab49-11e6-9823-8b2885c5e1d4.PNG)

Acceptance criteria: The link appears in the header with appropriate styling.

Success metrics:

- Decrease clicks into 'tools' to one click for 50% of users.

- Ensure that power users are happy about the location of their 'super user navigation item' through qualitative research.

**Comment by matthewcrist** [comment] 2016-12-09 01:51
@asalsman the styles have the link bumping up against the avatar. Also, when on mobile, the tools link shouldn't be added to the main navigation as it causes tools to be there twice.

**Comment by asalsman** [comment] 2016-12-12 13:52
@matthewcrist Where can I see the display you're referring to? In all my local testing, this was displaying as intended.

**Comment by matthewcrist** [comment] 2016-12-13 20:47
@asalsman try on edit-stg-hub.boston.gov

**Comment by asalsman** [comment] 2017-01-09 18:16
Didn't have a user icon showing up for me locally before. I have it now and a fix about to be committed.

**Closed** 2017-01-20 16:10 UTC
Labels: enhancement, Hub only
