### ISSUE TITLE
Related content "Neighborhoods" field and checkboxes appear in Posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#442] opened 2017-02-02 14:57 UTC
Only the checkboxes for neighborhoods should appear, not the neighborhoods field. The screenshot below shows that both are present. Ref  #306 and #392 

Example node on staging: 11561

![neighborhoods-posts](https://cloud.githubusercontent.com/assets/3886936/22554356/bf01757a-e92d-11e6-9f09-294f5900847f.PNG)

**Comment by asalsman** [comment] 2017-02-02 15:04
Addressed in PR #414

**Comment by hackajesse** [comment] 2017-02-07 14:29
Not quite right. Neighborhoods as a related content field now appears above the sidebar tabs (per the screenshot below) when creating a post. It shouldn't be present at all. Moving back to In Progress.

![post-neighborhoods-related-content](https://cloud.githubusercontent.com/assets/3886936/22695126/a3cd561e-ed17-11e6-94b2-80e56f2bc26e.PNG)

**Comment by matthewcrist** [comment] 2017-04-12 14:34
## Testing steps

- Goto post
- Verify that neighborhoods doesn't appear out of place

**Comment by reillyzlab** [comment] 2017-04-24 03:26
Still showing up on Hub. Okay on boston.gov

**Comment by matthewcrist** [comment] 2017-04-25 14:18
Helps if I actually deploy The Hub @reillyzlab. Try now.

**Comment by reillyzlab** [comment] 2017-04-27 20:51
@matthewcrist still on staging on Hub

**Comment by matthewcrist** [comment] 2017-04-27 23:16
This is gone on prod @reillyzlab.

**Comment by reillyzlab** [comment] 2017-05-05 20:14
Showing up on prod. on Hub again.

**Comment by jimafisk** [comment] 2017-07-24 16:03
I cannot reproduce this issue locally or on stg for Boston or Hub. @reillyzlab was this taken care of?

**Comment by matthewcrist** [comment] 2017-08-17 16:50
This is fixed.

**Closed** 2017-08-17 16:49 UTC
Labels: bug, work in progress
