### ISSUE TITLE
Fix styling issue with bullets in public notices

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#682] opened 2017-05-18 16:36 UTC
You can see the styling issue here on production:

https://edit.boston.gov/public-notices/25781

Basically, the bullets in the "description" text of a discussion topic render as numbers instead of bullets. <ol> tags also show up as decimals, and take into account the numbering of the discussion topics.

![image](https://cloud.githubusercontent.com/assets/7929556/26213318/9458d6f6-3bc6-11e7-9576-044a054801f8.png)

![image](https://cloud.githubusercontent.com/assets/7929556/26213329/9dccfabe-3bc6-11e7-8ddb-d9847a12ff50.png)

**Comment by matthewcrist** [comment] 2017-05-18 18:08
Closing as a dupe of #263

**Closed by matthewcrist** 2017-05-18 18:08 UTC
Labels: bug
